const foods=[['Pechuga de pollo',165,31,0,3.6],['Arroz cocido',130,2.7,28,0.3],['Arroz crudo',360,7,79,0.7],['Huevo',143,12.6,0.7,9.5],['Avena',389,16.9,66.3,6.9],['Plátano',89,1.1,22.8,0.3],['Pan integral',247,13,41,4.2],['Leche semidesnatada',46,3.3,4.8,1.6],['Yogur natural',61,3.5,4.7,3.3],['Atún al natural',116,26,0,1],['Salmón',208,20,0,13],['Patata cocida',87,1.9,20,0.1],['Pasta cocida',158,5.8,30.9,0.9],['Lentejas cocidas',116,9,20,0.4],['Aguacate',160,2,8.5,14.7],['Aceite de oliva',884,0,0,100],['Manzana',52,0.3,14,0.2],['Almendras',579,21,22,50],['Pechuga de pavo',104,24,0,1],['Tomate',18,0.9,3.9,0.2]];
let profile=JSON.parse(localStorage.getItem('nf_profile')||'null'), log=JSON.parse(localStorage.getItem('nf_log')||'[]'), selected=null;
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='home')render();}
function saveProfile(){let a=+age.value,h=+height.value,w=+weight.value;if(!a||!h||!w)return alert('Completa tus datos');let bmr=10*w+6.25*h-5*a+(sex.value==='m'?5:-161),tdee=bmr*+activity.value,goalv=goal.value,target=Math.round((tdee+(goalv==='lose'?-350:goalv==='gain'?250:0))/10)*10,pr=Math.round(w*(goalv==='gain'?1.8:1.6)),fat=Math.round(target*.25/9),carb=Math.round((target-pr*4-fat*9)/4);profile={target,pr,fat,carb,goal:goal.options[goal.selectedIndex].text};localStorage.setItem('nf_profile',JSON.stringify(profile));go('home')}
function openFood(){document.getElementById('foodModal').classList.add('open');renderFoods()}function closeFood(){document.getElementById('foodModal').classList.remove('open');document.getElementById('amountBox').hidden=true;selected=null}
function renderFoods(){let q=document.getElementById('search').value.toLowerCase();document.getElementById('foodList').innerHTML=foods.filter(f=>f[0].toLowerCase().includes(q)).map((f,i)=>`<div class="food" onclick="selectFood(${i})"><b>${f[0]}</b><small>${f[1]} kcal · ${f[2]}g proteína · ${f[3]}g carbos · ${f[4]}g grasa / 100g</small></div>`).join('')}
function selectFood(i){selected=foods[i];document.getElementById('foodName').textContent=selected[0];document.getElementById('amountBox').hidden=false;document.getElementById('amount').focus()}
function addFood(){if(!selected)return;let g=+document.getElementById('amount').value||100,m=document.getElementById('meal').value,k=g/100;log.push({id:Date.now(),food:selected[0],meal:m,g,kcal:selected[1]*k,p:selected[2]*k,c:selected[3]*k,f:selected[4]*k});localStorage.setItem('nf_log',JSON.stringify(log));closeFood();render()}
function del(id){log=log.filter(x=>x.id!==id);localStorage.setItem('nf_log',JSON.stringify(log));render()}
function render(){let totals=log.reduce((a,x)=>({k:a.k+x.kcal,p:a.p+x.p,c:a.c+x.c,f:a.f+x.f}),{k:0,p:0,c:0,f:0});document.getElementById('kcal').textContent=Math.round(totals.k);document.getElementById('p').textContent=Math.round(totals.p)+' g';document.getElementById('c').textContent=Math.round(totals.c)+' g';document.getElementById('f').textContent=Math.round(totals.f)+' g';let target=profile?.target;if(target){document.getElementById('remaining').textContent=`Te quedan ${Math.max(0,Math.round(target-totals.k))} kcal`;document.getElementById('targetText').textContent=`Objetivo: ${target} kcal`;[['pb',totals.p,profile.pr],['cb',totals.c,profile.carb],['fb',totals.f,profile.fat]].forEach(([id,v,t])=>document.getElementById(id).style.width=Math.min(100,v/t*100)+'%')}else{document.getElementById('remaining').textContent='Configura tus objetivos';document.getElementById('targetText').textContent='Puedes usar el contador sin registrarte'}document.getElementById('meals').innerHTML=['Desayuno','Comida','Merienda','Cena','Snack'].map(m=>{let arr=log.filter(x=>x.meal===m),sum=arr.reduce((s,x)=>s+x.kcal,0);return `<div class="meal"><h3>${m}<span>${Math.round(sum)} kcal</span></h3>${arr.length?arr.map(x=>`<div class="foodrow"><span>${x.food} · ${x.g}g</span><span>${Math.round(x.kcal)} kcal <button onclick="del(${x.id})">×</button></span></div>`).join(''):'<div class="empty">+ Añadir alimento desde el botón de arriba</div>'}</div>`}).join('')}
if(profile){go('home')}else{go('welcome')}