const foods=[['Pechuga de pollo',165,31,0,3.6],['Pechuga de pavo',104,24,0,1],['Atún al natural',116,26,0,1],['Salmón',208,20,0,13],['Huevo',143,12.6,.7,9.5],['Arroz cocido',130,2.7,28,.3],['Arroz crudo',360,7,79,.7],['Pasta cocida',158,5.8,30.9,.9],['Avena',389,16.9,66.3,6.9],['Pan integral',247,13,41,4.2],['Patata cocida',87,1.9,20,.1],['Lentejas cocidas',116,9,20,.4],['Garbanzos cocidos',164,8.9,27.4,2.6],['Leche semidesnatada',46,3.3,4.8,1.6],['Yogur natural',61,3.5,4.7,3.3],['Plátano',89,1.1,22.8,.3],['Manzana',52,.3,14,.2],['Tomate',18,.9,3.9,.2],['Aguacate',160,2,8.5,14.7],['Almendras',579,21,22,50],['Aceite de oliva',884,0,0,100],['Brócoli',35,2.4,7.2,.4],['Zanahoria',41,.9,9.6,.2],['Queso fresco',174,11,3,13],['Ternera magra',172,26,0,7],['Cerdo magro',143,21,0,6],['Merluza',89,18,0,1.8],['Gamba',99,24,0,0.3],['Naranja',47,.9,11.8,.1],['Fresas',32,.7,7.7,.3],['Kiwi',61,1.1,14.7,.5],['Cacahuetes',567,25.8,16.1,49.2]];
let profile=JSON.parse(localStorage.getItem('nf_profile_v3')||'null'),log=JSON.parse(localStorage.getItem('nf_log_v3')||'[]'),water=+localStorage.getItem('nf_water_v3')||0,favs=JSON.parse(localStorage.getItem('nf_favs_v3')||'[]'),history=JSON.parse(localStorage.getItem('nf_history_v3')||'[]'),selected=null;
const $=id=>document.getElementById(id);
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));if(id==='home')render();if(id==='progress')renderProgress();if(id==='favorites')renderFavorites();}
function saveProfile(){let a=+$('age').value,h=+$('height').value,w=+$('weight').value;if(!a||!h||!w)return alert('Completa edad, altura y peso.');let bmr=10*w+6.25*h-5*a+($('sex').value==='m'?5:-161),tdee=bmr*+$('activity').value,g=$('goal').value,kcal=Math.round((tdee+(g==='lose'?-350:g==='gain'?250:0))/10)*10,protein=Math.round(w*(g==='gain'?1.8:1.6)),fat=Math.round(kcal*.25/9),carb=Math.max(0,Math.round((kcal-protein*4-fat*9)/4));profile={kcal,protein,carb,fat};localStorage.setItem('nf_profile_v3',JSON.stringify(profile));go('home')}
function clearProfile(){profile=null;localStorage.removeItem('nf_profile_v3');go('home')}
function openFood(){if(!$('modal'))return;$('modal').classList.add('open');$('search').value='';$('amountBox').hidden=true;renderFoods();setTimeout(()=>$('search').focus(),100)}
function closeFood(){$('modal').classList.remove('open');selected=null}
function renderFoods(){let q=$('search').value.toLowerCase();$('foodList').innerHTML=foods.filter(f=>f[0].toLowerCase().includes(q)).map((f,i)=>`<div class="food" onclick="selectFood(${i})"><b>${f[0]} ${favs.includes(f[0])?'⭐':''}</b><small>${f[1]} kcal · ${f[2]} g proteína · ${f[3]} g carbos · ${f[4]} g grasa / 100 g</small></div>`).join('')||'<p>Sin resultados.</p>'}
function selectFood(i){selected=foods[i];$('foodName').textContent=selected[0];$('foodInfo').textContent=`${selected[1]} kcal · ${selected[2]} g proteína · ${selected[3]} g carbos · ${selected[4]} g grasa / 100 g`;$('amountBox').hidden=false}
function toggleFavorite(){if(!selected)return;let n=selected[0];favs=favs.includes(n)?favs.filter(x=>x!==n):[...favs,n];localStorage.setItem('nf_favs_v3',JSON.stringify(favs));renderFoods()}
function addFood(){if(!selected)return;let g=+$('amount').value||100,m=$('meal').value,k=g/100;log.push({id:Date.now(),food:selected[0],meal:m,g,kcal:selected[1]*k,p:selected[2]*k,c:selected[3]*k,f:selected[4]*k});localStorage.setItem('nf_log_v3',JSON.stringify(log));saveHistory();closeFood();render()}
function del(id){log=log.filter(x=>x.id!==id);localStorage.setItem('nf_log_v3',JSON.stringify(log));render()}
function addWater(){water=Math.min(5000,water+250);localStorage.setItem('nf_water_v3',water);render()}
function totals(){return log.reduce((a,x)=>({k:a.k+x.kcal,p:a.p+x.p,c:a.c+x.c,f:a.f+x.f}),{k:0,p:0,c:0,f:0})}
function saveHistory(){let t=totals(),key=new Date().toISOString().slice(0,10);history=history.filter(x=>x.date!==key);history.unshift({date:key,kcal:Math.round(t.k),foods:log.length});history=history.slice(0,14);localStorage.setItem('nf_history_v3',JSON.stringify(history))}
function render(){let t=totals();$('kcal').textContent=Math.round(t.k);$('p').textContent=Math.round(t.p)+' g';$('c').textContent=Math.round(t.c)+' g';$('f').textContent=Math.round(t.f)+' g';$('foodCount').textContent=log.length+' alimento'+(log.length===1?'':'s');if(profile){$('targetKcal').textContent=' / '+profile.kcal;$('remaining').textContent=t.k>=profile.kcal?`Has alcanzado tu objetivo de ${profile.kcal} kcal`:`Te quedan ${Math.round(profile.kcal-t.k)} kcal`;$('pt').textContent=`${Math.round(t.p)} / ${profile.protein} g`;$('ct').textContent=`${Math.round(t.c)} / ${profile.carb} g`;$('ft').textContent=`${Math.round(t.f)} / ${profile.fat} g`;[['pb',t.p,profile.protein],['cb',t.c,profile.carb],['fb',t.f,profile.fat]].forEach(([id,v,m])=>$(id).style.width=Math.min(100,v/m*100)+'%');let pct=Math.min(100,t.k/profile.kcal*100);$('kcalPct').textContent=Math.round(pct)+'%';document.querySelector('.donut').style.setProperty('--deg',pct*3.6+'deg')}else{$('targetKcal').textContent='';$('remaining').textContent='Configura tu perfil para ver objetivos personalizados';$('kcalPct').textContent='—';['pt','ct','ft'].forEach(id=>$(id).textContent='Sin objetivo');['pb','cb','fb'].forEach(id=>$(id).style.width='0%')}$('waterText').textContent=(water/1000).toFixed(1).replace('.',',')+' / 2,5 L';$('waterBar').style.width=Math.min(100,water/25)+'%';$('meals').innerHTML=['Desayuno','Comida','Merienda','Cena','Snack'].map(m=>{let a=log.filter(x=>x.meal===m),sum=a.reduce((s,x)=>s+x.kcal,0);return `<div class="meal"><div class="mealhead"><b>${m}</b><span>${Math.round(sum)} kcal</span></div>${a.length?a.map(x=>`<div class="foodrow"><span>${x.food} · ${x.g} g</span><span>${Math.round(x.kcal)} kcal <button onclick="del(${x.id})">×</button></span></div>`).join(''):'<div class="empty">Sin alimentos registrados</div>'}</div>`}).join('')}
function generateDay(){let options=[['Desayuno','Avena con leche y plátano','Avena + leche + plátano'],['Comida','Pollo con arroz y brócoli','Pollo + arroz + brócoli'],['Merienda','Yogur con fresas y almendras','Yogur + fresas + almendras'],['Cena','Merluza con patata y tomate','Merluza + patata + tomate']];$('dayPlan').innerHTML='<div class="daycard"><h3>Plan orientativo</h3>'+options.map(x=>`<div class="daymeal"><b>${x[0]}</b>${x[1]}<small>${x[2]}</small></div>`).join('')+'</div>'}
function renderProgress(){$('todayKcal').textContent=Math.round(totals().k);$('todayFoods').textContent=log.length;$('favCount').textContent=favs.length;$('history').innerHTML=history.length?history.map(x=>`<div class="historyrow"><span>${x.date}</span><b>${x.kcal} kcal · ${x.foods} alimentos</b></div>`).join(''):'<div class="coming">Todavía no hay historial.</div>'}
function renderFavorites(){$('favoritesList').innerHTML=favs.length?favs.map(n=>`<div class="meal"><b>${n}</b><button class="ghost" onclick="quickFavorite('${n.replace(/'/g,"\\'")}')">Añadir</button></div>`).join(''):'<div class="coming">Todavía no tienes favoritos.</div>'}
function quickFavorite(n){let i=foods.findIndex(f=>f[0]===n);if(i>=0){openFood();selectFood(i)}}
function ask(q){$('chatInput').value=q;sendChat()}
function sendChat(){let q=$('chatInput').value.trim();if(!q)return;let box=$('chatbox');box.innerHTML+=`<div class="bubble user">${q}</div>`;let t=totals(),ans;if(q.toLowerCase().includes('proteína'))ans=profile?`Llevas ${Math.round(t.p)} g de proteína de ${profile.protein} g objetivo.`:`Llevas ${Math.round(t.p)} g de proteína. Configura tu perfil para tener una meta.`;else if(q.toLowerCase().includes('cenar')){let rem=profile?Math.max(0,Math.round(profile.kcal-t.k)):600;ans=`Te quedan aproximadamente ${rem} kcal. Una idea sencilla: merluza con patata y verduras, ajustando la cantidad a lo que te quede.`}else ans='Con lo que llevas hoy, priorizaría una comida con proteína, verduras y una fuente de carbohidratos ajustada a tus calorías restantes. Recuerda que soy un asistente orientativo, no sustituyo a un profesional.';box.innerHTML+=`<div class="bubble ai">${ans}</div>`;box.scrollTop=box.scrollHeight;$('chatInput').value=''}
$('date').textContent=new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(new Date());render();